apiVersion: v1
items:
- apiVersion: stable.example.com/v1
  kind: cronTab
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"stable.example.com/v1","kind":"cronTab","metadata":{"annotations":{},"name":"my-new-obj","namespace":"default"},"spec":{"cronSpec":"* * * * */5","image":"tasdidur/mini-server"}}
    creationTimestamp: "2021-10-14T05:16:33Z"
    generation: 1
    name: my-new-obj
    namespace: default
    resourceVersion: "538083"
    uid: 9df8f6e9-391f-47e3-88a3-95c9a6e20a8a
  spec:
    cronSpec: '* * * * */5'
    image: tasdidur/mini-server
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
